/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto-generated by qswagger (https://github.com/Patrolin/qswagger)
 * Do NOT edit it manually
 */
import {AttachmentDeleteRequestDto} from '../models/AttachmentDeleteRequestDto';
import {AttachmentMetadataDto} from '../models/AttachmentMetadataDto';
import * as runtime from '../runtime';

export type attachmentGet_attachmentId_Get_PathParams = {
    attachmentId: string;
};
export type attachmentUpload_Post_MultipartBody = {
    clientId: string;
    messageId: string;
    attachment: Blob;
};
export class AttachmentControllerApi extends runtime.BaseAPI {
    async attachmentDelete_Post_Raw(body: AttachmentDeleteRequestDto, overrides: RequestInit = {}): Promise<Response> {
        let path = '/api/attachment/delete';
        const headers: runtime.HTTPHeaders = {};
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);
            if (tokenString) {
                headers["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        headers['Content-Type'] = 'application/json';
        return await this.request({
            method: 'POST',
            path,
            headers,
            body,
        }, overrides);
    }
    async attachmentDelete_Post(body: AttachmentDeleteRequestDto, overrides: RequestInit = {}): Promise<AttachmentMetadataDto> {
        const response = await this.attachmentDelete_Post_Raw(body, overrides);
        return await new runtime.JSONApiResponse(response, v => v as AttachmentMetadataDto).value();
    }
    async attachmentGet_attachmentId_Get_Raw(path_params: attachmentGet_attachmentId_Get_PathParams, overrides: RequestInit = {}): Promise<Response> {
        let path = '/api/attachment/get/{attachmentId}';
        path = path.replace('{attachmentId}', encodeURIComponent(String(path_params.attachmentId)));
        const headers: runtime.HTTPHeaders = {};
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);
            if (tokenString) {
                headers["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        return await this.request({
            method: 'GET',
            path,
            headers,
        }, overrides);
    }
    async attachmentGet_attachmentId_Get(path_params: attachmentGet_attachmentId_Get_PathParams, overrides: RequestInit = {}): Promise<Blob> {
        const response = await this.attachmentGet_attachmentId_Get_Raw(path_params, overrides);
        return await new runtime.JSONApiResponse(response, v => v as Blob).value();
    }
    async attachmentUpload_Post_Raw(body: attachmentUpload_Post_MultipartBody, overrides: RequestInit = {}): Promise<Response> {
        let path = '/api/attachment/upload';
        const headers: runtime.HTTPHeaders = {};
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);
            if (tokenString) {
                headers["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const formData = new FormData();
        formData.append('attachment', body.attachment);
        formData.append("messageId", body.messageId);
        formData.append("clientId", body.clientId);
        return await this.request({
            method: 'POST',
            path,
            headers,
            body: formData,
        }, overrides);
    }
    async attachmentUpload_Post(body: attachmentUpload_Post_MultipartBody, overrides: RequestInit = {}): Promise<AttachmentMetadataDto> {
        const response = await this.attachmentUpload_Post_Raw(body, overrides);
        return await new runtime.JSONApiResponse(response, v => v as AttachmentMetadataDto).value();
    }
}
