/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto-generated by qswagger (https://github.com/Patrolin/qswagger)
 * Do NOT edit it manually
 */
import {LoginRequestDto} from '../models/LoginRequestDto';
import {LoginResponseDto} from '../models/LoginResponseDto';
import {RefreshTokenRequestDto} from '../models/RefreshTokenRequestDto';
import {RefreshTokenResponseDto} from '../models/RefreshTokenResponseDto';
import * as runtime from '../runtime';

export class AuthenticationControllerApi extends runtime.BaseAPI {
    async authLogin_Post_Raw(body: LoginRequestDto, overrides: RequestInit = {}): Promise<Response> {
        let path = '/api/auth/login';
        const headers: runtime.HTTPHeaders = {};
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);
            if (tokenString) {
                headers["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        headers['Content-Type'] = 'application/json';
        return await this.request({
            method: 'POST',
            path,
            headers,
            body,
        }, overrides);
    }
    async authLogin_Post(body: LoginRequestDto, overrides: RequestInit = {}): Promise<LoginResponseDto> {
        const response = await this.authLogin_Post_Raw(body, overrides);
        return await new runtime.JSONApiResponse(response, v => v as LoginResponseDto).value();
    }
    async authRefreshToken_Post_Raw(body: RefreshTokenRequestDto, overrides: RequestInit = {}): Promise<Response> {
        let path = '/api/auth/refreshToken';
        const headers: runtime.HTTPHeaders = {};
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);
            if (tokenString) {
                headers["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        headers['Content-Type'] = 'application/json';
        return await this.request({
            method: 'POST',
            path,
            headers,
            body,
        }, overrides);
    }
    async authRefreshToken_Post(body: RefreshTokenRequestDto, overrides: RequestInit = {}): Promise<RefreshTokenResponseDto> {
        const response = await this.authRefreshToken_Post_Raw(body, overrides);
        return await new runtime.JSONApiResponse(response, v => v as RefreshTokenResponseDto).value();
    }
    async authRefresh_token_Post_Raw(body: RefreshTokenRequestDto, overrides: RequestInit = {}): Promise<Response> {
        let path = '/api/auth/refresh-token';
        const headers: runtime.HTTPHeaders = {};
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);
            if (tokenString) {
                headers["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        headers['Content-Type'] = 'application/json';
        return await this.request({
            method: 'POST',
            path,
            headers,
            body,
        }, overrides);
    }
    async authRefresh_token_Post(body: RefreshTokenRequestDto, overrides: RequestInit = {}): Promise<RefreshTokenResponseDto> {
        const response = await this.authRefresh_token_Post_Raw(body, overrides);
        return await new runtime.JSONApiResponse(response, v => v as RefreshTokenResponseDto).value();
    }
}
