/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto-generated by qswagger (https://github.com/Patrolin/qswagger)
 * Do NOT edit it manually
 */
import {MessageCreateRequestDto} from '../models/MessageCreateRequestDto';
import {MessageDeleteRequestDto} from '../models/MessageDeleteRequestDto';
import {MessageEditRequestDto} from '../models/MessageEditRequestDto';
import {MessagePageDtoOutboundChatMessage} from '../models/MessagePageDtoOutboundChatMessage';
import {OutboundChatMessage} from '../models/OutboundChatMessage';
import {Pageable} from '../models/Pageable';
import * as runtime from '../runtime';

export type messageList_Get_QueryParams = {
    destinationType: 'CHANNEL' | 'USER' | 'SELF';
    destination: string;
    pageable: Pageable;
    messageId?: string;
};
export class MessageControllerApi extends runtime.BaseAPI {
    async messageCreate_Post_Raw(body: MessageCreateRequestDto, overrides: RequestInit = {}): Promise<Response> {
        let path = '/api/message/create';
        const headers: runtime.HTTPHeaders = {};
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);
            if (tokenString) {
                headers["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        headers['Content-Type'] = 'application/json';
        return await this.request({
            method: 'POST',
            path,
            headers,
            body,
        }, overrides);
    }
    async messageCreate_Post(body: MessageCreateRequestDto, overrides: RequestInit = {}): Promise<OutboundChatMessage> {
        const response = await this.messageCreate_Post_Raw(body, overrides);
        return await new runtime.JSONApiResponse(response, v => v as OutboundChatMessage).value();
    }
    async messageDelete_Post_Raw(body: MessageDeleteRequestDto, overrides: RequestInit = {}): Promise<Response> {
        let path = '/api/message/delete';
        const headers: runtime.HTTPHeaders = {};
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);
            if (tokenString) {
                headers["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        headers['Content-Type'] = 'application/json';
        return await this.request({
            method: 'POST',
            path,
            headers,
            body,
        }, overrides);
    }
    async messageDelete_Post(body: MessageDeleteRequestDto, overrides: RequestInit = {}): Promise<OutboundChatMessage> {
        const response = await this.messageDelete_Post_Raw(body, overrides);
        return await new runtime.JSONApiResponse(response, v => v as OutboundChatMessage).value();
    }
    async messageEdit_Post_Raw(body: MessageEditRequestDto, overrides: RequestInit = {}): Promise<Response> {
        let path = '/api/message/edit';
        const headers: runtime.HTTPHeaders = {};
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);
            if (tokenString) {
                headers["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        headers['Content-Type'] = 'application/json';
        return await this.request({
            method: 'POST',
            path,
            headers,
            body,
        }, overrides);
    }
    async messageEdit_Post(body: MessageEditRequestDto, overrides: RequestInit = {}): Promise<OutboundChatMessage> {
        const response = await this.messageEdit_Post_Raw(body, overrides);
        return await new runtime.JSONApiResponse(response, v => v as OutboundChatMessage).value();
    }
    async messageList_Get_Raw(query: messageList_Get_QueryParams, overrides: RequestInit = {}): Promise<Response> {
        let path = '/api/message/list';
        const headers: runtime.HTTPHeaders = {};
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);
            if (tokenString) {
                headers["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        return await this.request({
            method: 'GET',
            path,
            headers,
            query,
        }, overrides);
    }
    async messageList_Get(query: messageList_Get_QueryParams, overrides: RequestInit = {}): Promise<MessagePageDtoOutboundChatMessage> {
        const response = await this.messageList_Get_Raw(query, overrides);
        return await new runtime.JSONApiResponse(response, v => v as MessagePageDtoOutboundChatMessage).value();
    }
}
