/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto-generated by qswagger (https://github.com/Patrolin/qswagger)
 * Do NOT edit it manually
 */
import {UserDto} from '../models/UserDto';
import * as runtime from '../runtime';

export class UserControllerApi extends runtime.BaseAPI {
    async userList_Get_Raw(overrides: RequestInit = {}): Promise<Response> {
        let path = '/api/user/list';
        const headers: runtime.HTTPHeaders = {};
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);
            if (tokenString) {
                headers["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        return await this.request({
            method: 'GET',
            path,
            headers,
        }, overrides);
    }
    async userList_Get(overrides: RequestInit = {}): Promise<UserDto[]> {
        const response = await this.userList_Get_Raw(overrides);
        return await new runtime.JSONApiResponse(response, v => v as UserDto[]).value();
    }
}
