/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto-generated by qswagger (https://github.com/Patrolin/qswagger)
 * Do NOT edit it manually
 */
import {InboundChatMessage} from './InboundChatMessage';

export type MessageCreateRequestDto = {
    destination: string;
    destinationType: 'CHANNEL' | 'USER' | 'SELF';
    message: InboundChatMessage;
};
