/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto-generated by qswagger (https://github.com/Patrolin/qswagger)
 * Do NOT edit it manually
 */
import {OutboundChatMessage} from './OutboundChatMessage';
import {PageableObject} from './PageableObject';

export type MessagePageDtoOutboundChatMessage = {
    messages: OutboundChatMessage[];
    pageable: PageableObject;
    totalCount: number;
    totalPages: number;
};
