/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto-generated by qswagger (https://github.com/Patrolin/qswagger)
 * Do NOT edit it manually
 */
import {SortObject} from './SortObject';

export type PageableObject = {
    offset: number;
    pageNumber: number;
    pageSize: number;
    paged: boolean;
    sort: SortObject[];
    unpaged: boolean;
};
