/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto-generated by qswagger (https://github.com/Patrolin/qswagger)
 * Do NOT edit it manually
 */
export type SortObject = {
    ascending: boolean;
    direction: string;
    ignoreCase: boolean;
    nullHandling: string;
    property: string;
};
